#!/usr/bin/env python3
"""Build Fragments_NNA/webpage.h from sim/bench.html.

The badge serves the test bench itself, so there is one source of truth for the
animation code rather than a third copy to keep in step. The bench is not edited
here -- this appends a stylesheet that hides the parts that only make sense on a
desk, and a script that keeps the page and the badge in agreement. Then it gzips
the result and emits it as a PROGMEM array.

Run it after changing sim/bench.html:
    python3 tools/make_webpage.py
"""
import gzip, pathlib, sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
SRC  = ROOT / "sim" / "bench.html"
OUT  = ROOT / "Fragments_NNA" / "webpage.h"

# Hide what belongs on a workbench rather than a phone: the emulated badge
# button (you are holding the real one), the developer overlays, and the notes
# about how the layout was worked out.
OVERLAY_CSS = """
<style>
  #badgeBtn, .toggle, .block:last-of-type { display: none !important; }
  .link { display: inline-flex; align-items: center; gap: 7px;
          font-family: var(--f-mono); font-size: 11px; letter-spacing: .09em;
          text-transform: uppercase; color: var(--silk-dim); }
  .link::before { content: ""; width: 8px; height: 8px; border-radius: 50%;
                  background: var(--warn); box-shadow: 0 0 8px var(--warn); }
  .link.on { color: var(--silk); }
  .link.on::before { background: #3ac87a; box-shadow: 0 0 8px #3ac87a; }
</style>
"""

# Keep the page and the badge in agreement. Rather than hooking every control,
# this watches the values the page already keeps and pushes them when they move,
# then polls so a press on the physical button shows up here too.
SYNC_JS = """
<script>
(function () {
  const bar = document.querySelector(".transport");
  const dot = document.createElement("span");
  dot.className = "link"; dot.textContent = "connecting";
  if (bar) bar.appendChild(dot);
  const link = ok => { dot.classList.toggle("on", ok); dot.textContent = ok ? "linked" : "offline"; };

  let sent = { m: -1, b: -1, h: -1 }, localAt = 0;

  setInterval(() => {
    if (gMode === sent.m && gBright === sent.b && gHue === sent.h) return;
    sent = { m: gMode, b: gBright, h: gHue }; localAt = Date.now();
    fetch(`/set?mode=${gMode}&bright=${gBright}&hue=${gHue}`, { method: "POST" })
      .then(r => link(r.ok)).catch(() => link(false));
  }, 200);

  setInterval(() => {
    if (Date.now() - localAt < 1200) return;      // let our own change settle first
    fetch("/state").then(r => r.json()).then(s => {
      link(true);
      if (s.mode !== gMode)    setMode(s.mode, false);
      if (s.bright !== gBright) { gBright = s.bright; syncBright(); }
      if (s.hue !== gHue)      { gHue = s.hue; updateInk(); syncHue(); }
      sent = { m: gMode, b: gBright, h: gHue };
    }).catch(() => link(false));
  }, 1500);
})();
</script>
"""

def main() -> int:
    if not SRC.exists():
        print(f"missing {SRC}", file=sys.stderr); return 1
    html = SRC.read_text(encoding="utf-8")
    html = html.replace("<title>Fragments Test Bench</title>",
                        "<title>Fragments Control</title>")
    html = html.replace("<h1>Fragments Test Bench</h1>",
                        "<h1>Fragments Control</h1>")
    html += OVERLAY_CSS + SYNC_JS

    raw = html.encode("utf-8")
    gz  = gzip.compress(raw, 9)

    # Note the comma joining the ROWS as well as the bytes -- without it the
    # array silently becomes a syntax error at the first line break.
    body = ",\n".join(
        "  " + ", ".join(f"0x{b:02x}" for b in gz[i:i + 16])
        for i in range(0, len(gz), 16))
    OUT.write_text(
        "// Generated by tools/make_webpage.py -- do not edit.\n"
        "// The badge serves the test bench, gzipped, so the animation code has one\n"
        f"// source of truth. {len(raw)} bytes of HTML in {len(gz)} bytes of flash.\n"
        "#pragma once\n#include <pgmspace.h>\n\n"
        f"#define WEBPAGE_GZ_LEN {len(gz)}\n"
        "const uint8_t WEBPAGE_GZ[] PROGMEM = {\n" + body + "\n};\n",
        encoding="utf-8")
    print(f"{OUT.relative_to(ROOT)}: {len(raw)} bytes -> {len(gz)} gzipped "
          f"({100 * len(gz) / len(raw):.0f}%)")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
